# Generated by Django 4.2 on 2025-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_document_department_document_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
