# GitHub Actions workflow to build and deploy Python app to Azure Web App - AdminChatBot

name: Build and deploy Python app to Azure Web App - AdminChatBot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add test steps here (e.g., pytest, unittest)

      - name: Zip artifact for deployment (flattened, excluding venv/.git/etc.)
        run: |
          mkdir temp-deploy
          shopt -s extglob
          cp -r !(venv|.git|.github|release.zip|temp-deploy) temp-deploy/
          cd temp-deploy
          zip -r ../release.zip .
          cd ..
          rm -rf temp-deploy

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DEF9ACEE6344881A304F807695829F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C67BB9B3BDD948229A21C6C2789FA28B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DBE119C674B48E69EDB3F6D2E36CCA1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AdminChatBot'
          slot-name: 'Production'
          package: release.zip
